import { Template } from '../types';

export const TEMPLATES: Template[] = [
  {
    id: 'blank',
    name: 'Blank Canvas',
    category: 'General',
    description: 'A totally clean workspace to start drawing freely.',
    iconName: 'Square',
    elements: [],
  },
  {
    id: 'brainstorm',
    name: 'Brainstorming Session',
    category: 'Brainstorm',
    description: 'Sticky notes organized into Ideas, Blockers, and Actions.',
    iconName: 'Lightbulb',
    elements: [
      // Title
      {
        type: 'text',
        x: 100,
        y: 60,
        width: 400,
        height: 50,
        text: '💡 Team Brainstorming Session',
        fontSize: 28,
        fontWeight: 'bold',
        fontFamily: 'sans',
        textColor: '#1e293b',
      },
      // Column 1: Ideas
      {
        type: 'rounded-rectangle',
        x: 100,
        y: 130,
        width: 260,
        height: 480,
        fillColor: '#f1f5f9',
        strokeColor: '#cbd5e1',
        strokeWidth: 2,
        strokeStyle: 'dashed',
        opacity: 0.8,
      },
      {
        type: 'text',
        x: 120,
        y: 145,
        width: 220,
        height: 30,
        text: '🚀 New Ideas',
        fontSize: 18,
        fontWeight: 'bold',
        textColor: '#334155',
      },
      {
        type: 'sticky-note',
        x: 120,
        y: 190,
        width: 220,
        height: 130,
        fillColor: '#fef08a', // Yellow
        text: 'Launch interactive canvas sharing for real-time review',
        fontSize: 14,
        textColor: '#854d0e',
      },
      {
        type: 'sticky-note',
        x: 120,
        y: 330,
        width: 220,
        height: 130,
        fillColor: '#bbf7d0', // Green
        text: 'Add vector export (SVG) for high quality rendering',
        fontSize: 14,
        textColor: '#166534',
      },

      // Column 2: Challenges
      {
        type: 'rounded-rectangle',
        x: 390,
        y: 130,
        width: 260,
        height: 480,
        fillColor: '#f1f5f9',
        strokeColor: '#cbd5e1',
        strokeWidth: 2,
        strokeStyle: 'dashed',
        opacity: 0.8,
      },
      {
        type: 'text',
        x: 410,
        y: 145,
        width: 220,
        height: 30,
        text: '⚠️ Challenges',
        fontSize: 18,
        fontWeight: 'bold',
        textColor: '#334155',
      },
      {
        type: 'sticky-note',
        x: 410,
        y: 190,
        width: 220,
        height: 130,
        fillColor: '#fbcfe8', // Pink
        text: 'Browser local storage limits for large image attachments',
        fontSize: 14,
        textColor: '#9d174d',
      },

      // Column 3: Action Items
      {
        type: 'rounded-rectangle',
        x: 680,
        y: 130,
        width: 260,
        height: 480,
        fillColor: '#f1f5f9',
        strokeColor: '#cbd5e1',
        strokeWidth: 2,
        strokeStyle: 'dashed',
        opacity: 0.8,
      },
      {
        type: 'text',
        x: 700,
        y: 145,
        width: 220,
        height: 30,
        text: '✅ Action Items',
        fontSize: 18,
        fontWeight: 'bold',
        textColor: '#334155',
      },
      {
        type: 'sticky-note',
        x: 700,
        y: 190,
        width: 220,
        height: 130,
        fillColor: '#bae6fd', // Blue
        text: 'Build IndexedDB auto-save manager with project thumbnails',
        fontSize: 14,
        textColor: '#075985',
      },
    ],
  },
  {
    id: 'mindmap',
    name: 'Mind Map',
    category: 'Mind Map',
    description: 'Central concept with connected sub-branches and ideas.',
    iconName: 'GitFork',
    elements: [
      // Central Node
      {
        id: 'mm_center',
        type: 'mindmap-node',
        x: 400,
        y: 280,
        width: 180,
        height: 80,
        fillColor: '#3b82f6',
        strokeColor: '#1d4ed8',
        strokeWidth: 2,
        text: 'NWS Draw Platform',
        fontSize: 18,
        fontWeight: 'bold',
        textColor: '#ffffff',
        isRootMindmap: true,
      },
      // Branch 1: Features
      {
        id: 'mm_b1',
        type: 'mindmap-node',
        x: 180,
        y: 160,
        width: 140,
        height: 60,
        fillColor: '#60a5fa',
        strokeColor: '#2563eb',
        strokeWidth: 2,
        text: 'Drawing Tools',
        fontSize: 14,
        fontWeight: 'bold',
        textColor: '#ffffff',
        parentId: 'mm_center',
      },
      {
        id: 'mm_b1_sub1',
        type: 'mindmap-node',
        x: 20,
        y: 120,
        width: 120,
        height: 45,
        fillColor: '#93c5fd',
        strokeColor: '#3b82f6',
        strokeWidth: 1.5,
        text: 'Freehand Pen',
        fontSize: 13,
        textColor: '#1e3a8a',
        parentId: 'mm_b1',
      },
      {
        id: 'mm_b1_sub2',
        type: 'mindmap-node',
        x: 20,
        y: 190,
        width: 120,
        height: 45,
        fillColor: '#93c5fd',
        strokeColor: '#3b82f6',
        strokeWidth: 1.5,
        text: 'Smart Connectors',
        fontSize: 13,
        textColor: '#1e3a8a',
        parentId: 'mm_b1',
      },
      // Branch 2: Storage
      {
        id: 'mm_b2',
        type: 'mindmap-node',
        x: 660,
        y: 160,
        width: 140,
        height: 60,
        fillColor: '#34d399',
        strokeColor: '#059669',
        strokeWidth: 2,
        text: 'Local Storage',
        fontSize: 14,
        fontWeight: 'bold',
        textColor: '#ffffff',
        parentId: 'mm_center',
      },
      {
        id: 'mm_b2_sub1',
        type: 'mindmap-node',
        x: 840,
        y: 130,
        width: 130,
        height: 45,
        fillColor: '#a7f3d0',
        strokeColor: '#10b981',
        strokeWidth: 1.5,
        text: 'IndexedDB',
        fontSize: 13,
        textColor: '#064e3b',
        parentId: 'mm_b2',
      },
      {
        id: 'mm_b2_sub2',
        type: 'mindmap-node',
        x: 840,
        y: 200,
        width: 130,
        height: 45,
        fillColor: '#a7f3d0',
        strokeColor: '#10b981',
        strokeWidth: 1.5,
        text: 'No Sign Up',
        fontSize: 13,
        textColor: '#064e3b',
        parentId: 'mm_b2',
      },
      // Branch 3: Export
      {
        id: 'mm_b3',
        type: 'mindmap-node',
        x: 420,
        y: 440,
        width: 140,
        height: 60,
        fillColor: '#f472b6',
        strokeColor: '#db2777',
        strokeWidth: 2,
        text: 'Export Formats',
        fontSize: 14,
        fontWeight: 'bold',
        textColor: '#ffffff',
        parentId: 'mm_center',
      },
      {
        id: 'mm_b3_sub1',
        type: 'mindmap-node',
        x: 260,
        y: 520,
        width: 110,
        height: 40,
        fillColor: '#fbcfe8',
        strokeColor: '#ec4899',
        strokeWidth: 1.5,
        text: 'PNG / SVG',
        fontSize: 12,
        textColor: '#831843',
        parentId: 'mm_b3',
      },
      {
        id: 'mm_b3_sub2',
        type: 'mindmap-node',
        x: 600,
        y: 520,
        width: 130,
        height: 40,
        fillColor: '#fbcfe8',
        strokeColor: '#ec4899',
        strokeWidth: 1.5,
        text: '.nwsdraw Project',
        fontSize: 12,
        textColor: '#831843',
        parentId: 'mm_b3',
      },
    ],
  },
  {
    id: 'flowchart',
    name: 'Flowchart Architecture',
    category: 'Flowchart',
    description: 'Process workflow with start, decisions, actions, and DB.',
    iconName: 'Workflow',
    elements: [
      // Title
      {
        type: 'text',
        x: 100,
        y: 40,
        width: 350,
        height: 40,
        text: '🔄 User Authentication Flow',
        fontSize: 22,
        fontWeight: 'bold',
        textColor: '#0f172a',
      },
      // Start node
      {
        id: 'fc_start',
        type: 'flowchart-start',
        x: 100,
        y: 110,
        width: 140,
        height: 60,
        fillColor: '#dcfce7',
        strokeColor: '#16a34a',
        strokeWidth: 2,
        text: 'User Visits Site',
        fontSize: 14,
        fontWeight: 'bold',
        textColor: '#14532d',
      },
      // Process: Request Access
      {
        id: 'fc_proc1',
        type: 'flowchart-process',
        x: 100,
        y: 220,
        width: 160,
        height: 65,
        fillColor: '#e0f2fe',
        strokeColor: '#0284c7',
        strokeWidth: 2,
        text: 'Check Cached Session',
        fontSize: 13,
        textColor: '#0369a1',
      },
      // Connector 1
      {
        type: 'connector',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        startElementId: 'fc_start',
        endElementId: 'fc_proc1',
        startAnchor: 'bottom',
        endAnchor: 'top',
        strokeColor: '#64748b',
        strokeWidth: 2,
      },
      // Decision
      {
        id: 'fc_dec1',
        type: 'flowchart-decision',
        x: 100,
        y: 330,
        width: 160,
        height: 90,
        fillColor: '#fef3c7',
        strokeColor: '#d97706',
        strokeWidth: 2,
        text: 'Valid Token?',
        fontSize: 13,
        fontWeight: 'bold',
        textColor: '#78350f',
      },
      // Connector 2
      {
        type: 'connector',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        startElementId: 'fc_proc1',
        endElementId: 'fc_dec1',
        startAnchor: 'bottom',
        endAnchor: 'top',
        strokeColor: '#64748b',
        strokeWidth: 2,
      },
      // End / Dashboard
      {
        id: 'fc_end',
        type: 'flowchart-start',
        x: 350,
        y: 345,
        width: 150,
        height: 60,
        fillColor: '#dcfce7',
        strokeColor: '#16a34a',
        strokeWidth: 2,
        text: 'Grant Access',
        fontSize: 14,
        fontWeight: 'bold',
        textColor: '#14532d',
      },
      // Connector Yes
      {
        type: 'connector',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        startElementId: 'fc_dec1',
        endElementId: 'fc_end',
        startAnchor: 'right',
        endAnchor: 'left',
        strokeColor: '#16a34a',
        strokeWidth: 2,
        text: 'Yes',
      },
      // Database query
      {
        id: 'fc_db',
        type: 'flowchart-db',
        x: 100,
        y: 470,
        width: 160,
        height: 80,
        fillColor: '#f3e8ff',
        strokeColor: '#9333ea',
        strokeWidth: 2,
        text: 'Redirect to Login',
        fontSize: 13,
        textColor: '#581c87',
      },
      // Connector No
      {
        type: 'connector',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        startElementId: 'fc_dec1',
        endElementId: 'fc_db',
        startAnchor: 'bottom',
        endAnchor: 'top',
        strokeColor: '#dc2626',
        strokeWidth: 2,
        text: 'No',
      },
    ],
  },
  {
    id: 'wireframe',
    name: 'Website Wireframe',
    category: 'Wireframe',
    description: 'Browser frame with nav, hero section, card grid, and CTA.',
    iconName: 'Layout',
    elements: [
      // Browser Window
      {
        type: 'wireframe-browser',
        x: 100,
        y: 80,
        width: 700,
        height: 520,
        fillColor: '#ffffff',
        strokeColor: '#64748b',
        strokeWidth: 2,
        text: 'https://nwsdraw.com',
      },
      // Nav bar
      {
        type: 'wireframe-navbar',
        x: 110,
        y: 135,
        width: 680,
        height: 50,
        fillColor: '#f8fafc',
        strokeColor: '#cbd5e1',
        strokeWidth: 1.5,
        text: 'NWS Draw | Features | Pricing | Contact',
      },
      // Hero text
      {
        type: 'text',
        x: 140,
        y: 210,
        width: 400,
        height: 60,
        text: 'Think it. Draw it.',
        fontSize: 28,
        fontWeight: 'bold',
        textColor: '#0f172a',
      },
      // Subtext
      {
        type: 'text',
        x: 140,
        y: 260,
        width: 420,
        height: 40,
        text: 'The free, infinite visual workspace for diagrams & ideas.',
        fontSize: 14,
        textColor: '#475569',
      },
      // Call to action button
      {
        type: 'wireframe-button',
        x: 140,
        y: 310,
        width: 150,
        height: 45,
        fillColor: '#2563eb',
        strokeColor: '#1d4ed8',
        strokeWidth: 1,
        text: 'Start Drawing Now',
        fontSize: 14,
        textColor: '#ffffff',
      },
      // Hero Image Placeholder
      {
        type: 'wireframe-image',
        x: 520,
        y: 210,
        width: 250,
        height: 150,
        fillColor: '#e2e8f0',
        strokeColor: '#94a3b8',
        strokeWidth: 1.5,
        text: 'Hero Canvas Preview',
      },
      // 3 Feature Cards
      {
        type: 'wireframe-card',
        x: 140,
        y: 390,
        width: 190,
        height: 180,
        fillColor: '#ffffff',
        strokeColor: '#cbd5e1',
        strokeWidth: 1.5,
        text: '⚡ Instant Start\nNo account or signup needed. Open and sketch.',
      },
      {
        type: 'wireframe-card',
        x: 355,
        y: 390,
        width: 190,
        height: 180,
        fillColor: '#ffffff',
        strokeColor: '#cbd5e1',
        strokeWidth: 1.5,
        text: '🔒 Local First\nYour drawings stay safe inside IndexedDB storage.',
      },
      {
        type: 'wireframe-card',
        x: 570,
        y: 390,
        width: 190,
        height: 180,
        fillColor: '#ffffff',
        strokeColor: '#cbd5e1',
        strokeWidth: 1.5,
        text: '📐 Smart Connectors\nBuild flowcharts, mind maps, and wireframes.',
      },
    ],
  },
  {
    id: 'swot',
    name: 'SWOT Analysis',
    category: 'Planning',
    description: 'Strengths, Weaknesses, Opportunities, and Threats quadrant.',
    iconName: 'Grid',
    elements: [
      {
        type: 'text',
        x: 100,
        y: 40,
        width: 400,
        height: 40,
        text: '📊 SWOT Analysis Matrix',
        fontSize: 24,
        fontWeight: 'bold',
        textColor: '#0f172a',
      },
      // Quadrant 1: Strengths
      {
        type: 'rectangle',
        x: 100,
        y: 90,
        width: 320,
        height: 240,
        fillColor: '#dcfce7',
        strokeColor: '#22c55e',
        strokeWidth: 2,
      },
      {
        type: 'text',
        x: 115,
        y: 105,
        width: 200,
        height: 30,
        text: '💪 Strengths',
        fontSize: 18,
        fontWeight: 'bold',
        textColor: '#15803d',
      },
      {
        type: 'sticky-note',
        x: 120,
        y: 145,
        width: 280,
        height: 160,
        fillColor: '#fef08a',
        text: '• Fast local canvas performance\n• Free, zero signup barrier\n• Sleek UI with full touch support',
        fontSize: 13,
        textColor: '#854d0e',
      },
      // Quadrant 2: Weaknesses
      {
        type: 'rectangle',
        x: 440,
        y: 90,
        width: 320,
        height: 240,
        fillColor: '#fee2e2',
        strokeColor: '#ef4444',
        strokeWidth: 2,
      },
      {
        type: 'text',
        x: 455,
        y: 105,
        width: 200,
        height: 30,
        text: '⚠️ Weaknesses',
        fontSize: 18,
        fontWeight: 'bold',
        textColor: '#b91c1c',
      },
      {
        type: 'sticky-note',
        x: 460,
        y: 145,
        width: 280,
        height: 160,
        fillColor: '#fbcfe8',
        text: '• No live multi-user WebSocket server\n• Restricted to single device storage',
        fontSize: 13,
        textColor: '#9d174d',
      },
      // Quadrant 3: Opportunities
      {
        type: 'rectangle',
        x: 100,
        y: 350,
        width: 320,
        height: 240,
        fillColor: '#e0f2fe',
        strokeColor: '#0284c7',
        strokeWidth: 2,
      },
      {
        type: 'text',
        x: 115,
        y: 365,
        width: 200,
        height: 30,
        text: '🌟 Opportunities',
        fontSize: 18,
        fontWeight: 'bold',
        textColor: '#0369a1',
      },
      {
        type: 'sticky-note',
        x: 120,
        y: 405,
        width: 280,
        height: 160,
        fillColor: '#bae6fd',
        text: '• Deep integration with NWS Study & Tools\n• PWA offline installable support',
        fontSize: 13,
        textColor: '#075985',
      },
      // Quadrant 4: Threats
      {
        type: 'rectangle',
        x: 440,
        y: 350,
        width: 320,
        height: 240,
        fillColor: '#fef3c7',
        strokeColor: '#f59e0b',
        strokeWidth: 2,
      },
      {
        type: 'text',
        x: 455,
        y: 365,
        width: 200,
        height: 30,
        text: '🛡️ Threats',
        fontSize: 18,
        fontWeight: 'bold',
        textColor: '#b45309',
      },
      {
        type: 'sticky-note',
        x: 460,
        y: 405,
        width: 280,
        height: 160,
        fillColor: '#fde68a',
        text: '• Competing cloud canvas platforms\n• Browser cache clearing risk',
        fontSize: 13,
        textColor: '#78350f',
      },
    ],
  },
  {
    id: 'cloud-architecture',
    name: 'Cloud Microservices Architecture',
    mode: 'diagram',
    category: 'Flowchart',
    description: 'Cloud gateway, API load balancer, App servers, and Database.',
    iconName: 'Workflow',
    elements: [
      {
        type: 'text',
        x: 100,
        y: 40,
        width: 450,
        height: 40,
        text: '☁️ Cloud Infrastructure Architecture',
        fontSize: 22,
        fontWeight: 'bold',
        textColor: '#0f172a',
      },
      // Client
      {
        id: 'arch_client',
        type: 'arch-client',
        x: 100,
        y: 120,
        width: 140,
        height: 80,
        fillColor: '#e0f2fe',
        strokeColor: '#0284c7',
        strokeWidth: 2,
        text: 'Web & Mobile Client',
        textColor: '#0369a1',
      },
      // Cloud API Gateway
      {
        id: 'arch_gateway',
        type: 'arch-cloud',
        x: 320,
        y: 120,
        width: 160,
        height: 80,
        fillColor: '#e0e7ff',
        strokeColor: '#4f46e5',
        strokeWidth: 2,
        text: 'API Gateway',
        textColor: '#3730a3',
      },
      // Connector 1
      {
        type: 'connector',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        startElementId: 'arch_client',
        endElementId: 'arch_gateway',
        startAnchor: 'right',
        endAnchor: 'left',
        strokeColor: '#64748b',
        strokeWidth: 2,
        text: 'HTTPS / WSS',
      },
      // App Server
      {
        id: 'arch_server',
        type: 'arch-server',
        x: 550,
        y: 120,
        width: 150,
        height: 80,
        fillColor: '#dcfce7',
        strokeColor: '#16a34a',
        strokeWidth: 2,
        text: 'Microservice Cluster',
        textColor: '#14532d',
      },
      // Connector 2
      {
        type: 'connector',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        startElementId: 'arch_gateway',
        endElementId: 'arch_server',
        startAnchor: 'right',
        endAnchor: 'left',
        strokeColor: '#64748b',
        strokeWidth: 2,
      },
      // DB
      {
        id: 'arch_db',
        type: 'arch-database',
        x: 770,
        y: 120,
        width: 140,
        height: 80,
        fillColor: '#f3e8ff',
        strokeColor: '#9333ea',
        strokeWidth: 2,
        text: 'PostgreSQL DB',
        textColor: '#581c87',
      },
      // Connector 3
      {
        type: 'connector',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        startElementId: 'arch_server',
        endElementId: 'arch_db',
        startAnchor: 'right',
        endAnchor: 'left',
        strokeColor: '#64748b',
        strokeWidth: 2,
        text: 'SQL Query',
      },
    ],
  },
  {
    id: 'social-post-design',
    name: 'Instagram Graphic Design',
    mode: 'design',
    category: 'Social Media',
    description: '1080x1080 social media graphic with styled title, badge, and quote.',
    iconName: 'Layout',
    designPreset: 'instagram-post',
    canvasWidth: 1080,
    canvasHeight: 1080,
    elements: [
      // Background card
      {
        type: 'rectangle',
        x: 60,
        y: 60,
        width: 960,
        height: 960,
        fillColor: '#4f46e5',
        strokeColor: '#3730a3',
        strokeWidth: 0,
      },
      {
        type: 'asset-badge',
        x: 120,
        y: 120,
        width: 180,
        height: 40,
        badgeLabel: 'NWS DESIGN',
        fillColor: '#fef08a',
        strokeColor: '#ca8a04',
        textColor: '#854d0e',
      },
      {
        type: 'text',
        x: 120,
        y: 280,
        width: 800,
        height: 200,
        text: 'Visual Thinking\nWithout Boundaries',
        fontSize: 64,
        fontWeight: 'bold',
        fontFamily: 'display',
        textColor: '#ffffff',
      },
      {
        type: 'text',
        x: 120,
        y: 540,
        width: 800,
        height: 120,
        text: 'Draw flowcharts, mind maps, wireframes, and presentations in one unified canvas.',
        fontSize: 28,
        textColor: '#c7d2fe',
      },
      {
        type: 'rounded-rectangle',
        x: 120,
        y: 760,
        width: 320,
        height: 90,
        fillColor: '#ffffff',
        strokeColor: '#ffffff',
        text: 'Explore NWS Draw →',
        fontSize: 22,
        fontWeight: 'bold',
        textColor: '#4f46e5',
      },
    ],
  },
  {
    id: 'pitch-presentation',
    name: 'Pitch Deck Presentation',
    mode: 'presentation',
    category: 'Presentations',
    description: '3-slide presentation deck with Title, Problem/Solution, and Roadmap slides.',
    iconName: 'Grid',
    slides: [
      {
        id: 'slide_1',
        title: 'Title Slide',
        backgroundColor: '#0f172a',
        elements: [
          {
            id: 'sl1_1',
            createdAt: 100,
            updatedAt: 100,
            type: 'text',
            x: 200,
            y: 280,
            width: 1200,
            height: 120,
            text: 'NWS Draw — Visual Creation Layer',
            fontSize: 56,
            fontWeight: 'bold',
            textColor: '#ffffff',
            textAlign: 'center',
          },
          {
            id: 'sl1_2',
            createdAt: 100,
            updatedAt: 100,
            type: 'text',
            x: 300,
            y: 430,
            width: 1000,
            height: 80,
            text: 'Draw. Diagram. Design. Visualize. No signup required.',
            fontSize: 28,
            textColor: '#94a3b8',
            textAlign: 'center',
          },
        ],
      },
      {
        id: 'slide_2',
        title: 'The Solution',
        backgroundColor: '#ffffff',
        elements: [
          {
            id: 'sl2_1',
            createdAt: 100,
            updatedAt: 100,
            type: 'text',
            x: 150,
            y: 100,
            width: 800,
            height: 60,
            text: 'One Unified Canvas for All Visuals',
            fontSize: 40,
            fontWeight: 'bold',
            textColor: '#0f172a',
          },
          {
            id: 'sl2_2',
            createdAt: 100,
            updatedAt: 100,
            type: 'rounded-rectangle',
            x: 150,
            y: 220,
            width: 450,
            height: 380,
            fillColor: '#e0e7ff',
            strokeColor: '#6366f1',
            strokeWidth: 2,
            text: '⚡ Instant & Accessible\n\n• Zero registration or paywalls\n• Local-first IndexedDB storage\n• Works seamlessly on any screen',
            fontSize: 20,
            textColor: '#312e81',
          },
          {
            id: 'sl2_3',
            createdAt: 100,
            updatedAt: 100,
            type: 'rounded-rectangle',
            x: 650,
            y: 220,
            width: 450,
            height: 380,
            fillColor: '#dcfce7',
            strokeColor: '#22c55e',
            strokeWidth: 2,
            text: '🎨 Cross-Mode Creation\n\n• Switch between Whiteboard & Diagram\n• Build wireframes & slide decks\n• Export crisp PNG, SVG, or PDF',
            fontSize: 20,
            textColor: '#14532d',
          },
        ],
      },
      {
        id: 'slide_3',
        title: 'Product Roadmap',
        backgroundColor: '#f8fafc',
        elements: [
          {
            id: 'sl3_1',
            createdAt: 100,
            updatedAt: 100,
            type: 'text',
            x: 150,
            y: 100,
            width: 800,
            height: 60,
            text: 'Execution Roadmap',
            fontSize: 40,
            fontWeight: 'bold',
            textColor: '#0f172a',
          },
          {
            id: 'sl3_2',
            createdAt: 100,
            updatedAt: 100,
            type: 'sticky-note',
            x: 150,
            y: 220,
            width: 320,
            height: 220,
            fillColor: '#fef08a',
            text: 'Q1: Core Canvas & Diagramming\n• Smart connectors\n• Shape libraries',
            fontSize: 18,
            textColor: '#854d0e',
          },
          {
            id: 'sl3_3',
            createdAt: 100,
            updatedAt: 100,
            type: 'sticky-note',
            x: 520,
            y: 220,
            width: 320,
            height: 220,
            fillColor: '#bae6fd',
            text: 'Q2: Workspace Expansion\n• Design preset sizes\n• Presentation slides mode',
            fontSize: 18,
            textColor: '#075985',
          },
          {
            id: 'sl3_4',
            createdAt: 100,
            updatedAt: 100,
            type: 'sticky-note',
            x: 890,
            y: 220,
            width: 320,
            height: 220,
            fillColor: '#fbcfe8',
            text: 'Q3: Ecosystem Integration\n• Export & Sync across NWS apps\n• Infinite canvas scaling',
            fontSize: 18,
            textColor: '#831843',
          },
        ],
      },
    ],
    elements: [],
  },
];
